name: Run tests

on: workflow_call

jobs:
  run_tests:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 27017 && echo "MongoDB is ready" && exit 0
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB did not become ready in time" && exit 1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Download env.toml file
        run: gcloud storage cp ${{ secrets.GCP_GITHUB_ACTIONS_ENV_TOML_PATH }} .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for running tests
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          target: image_for_running_tests_in_github_actions
          tags: app:image_for_running_tests_in_github_actions
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: app:image_for_running_tests_in_github_actions
          run: poetry run pytest src/tests/ -c pytest.ini
