name: on-push-test

on:
  push:
    branches: ["test/*"]
  workflow_dispatch:

jobs:
  deploy_to_app_engine:
    uses: ./.github/workflows/called-deploy-to-app-engine.yml
    secrets: inherit
    with:
      environment: "test"

  deploy_before_create_user_cloud_function:
    uses: ./.github/workflows/called-deploy-testing_m2m_via_google_signed_id_token-cloud-function.yml
    secrets: inherit
    with:
      environment: "test"
