name: on-push-test

on:
  push:
    branches: ["main"]

jobs:
  get_changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      poetry_dependecies: ${{ steps.changes.outputs.dependency_versions }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            fastapi_hello_world:
              - 'fastapi_hello_world/**'
            poetry_dependecies:
              - 'poetry.lock'
            hello_world_cloud_function:
              - 'cloud_functions.hello_world/**'

  run_tests:
    if: ${{ needs.get_changes.outputs.fastapi_hello_world == 'true' || needs.get_changes.outputs.poetry_dependencies == 'true' }}
    needs: get_changes
    uses: ./.github/workflows/called-run-tests.yml
    secrets: inherit

  deploy_hello_world_cloud_function:
    if: ${{ needs.get_changes.outputs.hello_world_cloud_function == 'true' }}
    needs: get_changes
    uses: ./.github/workflows/called-deploy_hello_world_cloud_function.yml
    secrets: inherit

  deploy_to_app_engine:
    needs: run_tests
    uses: ./.github/workflows/called-deploy_to_app_engine.yml
    secrets: inherit
