name: on-push-test

on:
  push:
    branches: ["test**"]

jobs:
  get_changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      poetry_dependecies: ${{ steps.changes.outputs.dependency_versions }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            fastapi_hello_world:
              - 'fastapi_hello_world/**'
            poetry_dependecies:
              - 'poetry.lock'

  # TODO (16.03) need to update according to different stands
  # run_tests:
  #   if: ${{ needs.get_changes.outputs.fastapi_hello_world == 'true' || needs.get_changes.outputs.poetry_dependencies == 'true' }}
  #   needs: get_changes
  #   uses: ./.github/workflows/called-run-tests.yml
  #   secrets: inherit
  #   with:
  #     environment: "test"

  deploy_to_app_engine:
    # needs: run_tests
    uses: ./.github/workflows/called-deploy-to-app-engine.yml
    secrets: inherit
    with:
      environment: "test"

  # TODO (16.03) need to update according to different stands
  # deploy_before_create_user_cloud_function:
  #   if: ${{ needs.get_changes.outputs.hello_world_cloud_function == 'true' }}
  #   needs: get_changes
  #   uses: ./.github/workflows/called-deploy_hello_world_cloud_function.yml
  #   secrets: inherit
  #   with:
  #     environment: "test"
